# Generated by Django 6.0 on 2025-12-18 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, default=2025, null=True, verbose_name='year')),
                ('term', models.PositiveSmallIntegerField(blank=True, default=1, help_text='1=First, 2=Second, 3=Summer', null=True, verbose_name='term')),
                ('code', models.PositiveIntegerField(editable=False, unique=True, verbose_name='semester code')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('min_units', models.PositiveSmallIntegerField(blank=True, default=12, null=True)),
                ('max_units', models.PositiveSmallIntegerField(blank=True, default=24, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
