# Generated by Django 6.0 on 2025-12-18 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, null=True, verbose_name='day of week')),
                ('time_slot', models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('14-16', '14:00 - 16:00'), ('16-18', '16:00 - 18:00')], max_length=10, verbose_name='time slot')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='course code')),
                ('unit', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, null=True, related_name='required_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='capacity')),
                ('prof_name', models.CharField(blank=True, default='نامشخص', max_length=50, null=True, verbose_name='prof_name')),
                ('semester', models.IntegerField(blank=True, default=20251, max_length=30, null=True, verbose_name='semester')),
                ('group_code', models.CharField(max_length=10, verbose_name='group code')),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='course')),
                ('sessions', models.ManyToManyField(blank=True, null=True, related_name='course_schedules', to='courses.session')),
            ],
            options={
                'verbose_name': 'course offering',
                'verbose_name_plural': 'course offering',
            },
        ),
    ]
